name = "worker-typescript-template"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true

[dev]
local_protocol = "http"
upstream_protocol = "http"

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"
